apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app-depl
spec:
  selector:
    matchLabels:
      app: myapp-react
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp-react
    spec:
      containers:
      - name: myapp-react
        image: premdevdis/test-react-vite
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: my-react-srv
spec:
  type: NodePort
  selector:
    app: myapp-react
  ports:
    - name: my-app
      port: 5000
      targetPort: 5000
